### ISSUE TITLE
Zero-shot Video Captioning Problem

### ISSUE THREAD

**Issue by BruceChen15** [X-PLUG/mPLUG#3]
Hi, I encounter a problem. I think you did not release the ViT-L-14 or ViT-B-16 models.
Can you slove these problem?
thank you
![image](https://github.com/X-PLUG/mPLUG/assets/105723918/4311c21e-8aff-429a-bf6f-0e6355af7f06)

**Comment by MAGAer13** [comment]
Please refer to the original version of CLIP.
